In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

def prt(*pVPK) :
    print(*pVPK, sep = '\n\n', end = '\n\n')
    
import numpy as np
import datetime, sys    

### [예제1] Python List 와 NumPy 배열

* numpy 배열 함수는 실수, 정수, 문자를 다 가질 수 있음

    ex) np.array(['A','B'])

In [2]:
# [1]
# list와 list comprehension 생성
# numpy 보다 느림

start = datetime.datetime.now()
l = list(range(20000000))
a = [i+2 for i in l]
end = datetime.datetime.now()

print('time: ', end - start)
print('size: ', sys.getsizeof(l))

time:  0:00:01.417604
size:  160000056


In [3]:
# [2]
# numpy 배열 생성
# python list 보다 빠르고 크기도 작음

# arrange : array 생성 함수

start = datetime.datetime.now()
a = np.arange(20000000)
a = a + 2
end = datetime.datetime.now()

print('time: ', end - start)
print('size: ', sys.getsizeof(a))

time:  0:00:00.231287
size:  80000096


### [예제2] ndarry 생성

In [4]:
# [1-1] 

a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a3 = np.array([a2, a2])

print(type(a1), a1.ndim, a1.shape, a1.dtype) # type=np.ndarray, ndim=1(1차원), shape=3, dtype=int32
print(type(a2), a2.ndim, a2.shape, a2.dtype) # type=np.ndarray, ndim=2(2차원), shape=(4,3), dtype=int 
print(type(a3), a3.ndim, a3.shape, a3.dtype) # type=np.ndarray, ndim=1(3차원), shape=(2,4,3), dtype=int 

<class 'numpy.ndarray'> 1 (3,) int32
<class 'numpy.ndarray'> 2 (4, 3) int32
<class 'numpy.ndarray'> 3 (2, 4, 3) int32


In [5]:
# [1-2] 

a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a3 = np.array([a2, a2])

print(a1[1], a1[1:], a2[1][2], a2[1,2])
print(a2[0:2][1:]) # a2[0:2] 결과에 [1:] 실행
print(a2[0:2, 1:]) # a2의 0~1행, 1~마지막열 추출

2 [2 3] 6 6
[[4 5 6]]
[[2 3]
 [5 6]]


In [6]:
# [2-1] 

a = np.array((1,2,3,4))
b = np.array(range(0,10), dtype = float) # dtype = float : float64 타입으로 생성
c = np.array(a, dtype = float)
d = np.arange(5)

print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)
print(d, d.dtype)

[1 2 3 4] int32
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[1. 2. 3. 4.] float64
[0 1 2 3 4] int32


In [7]:
# [2-2] 

e = np.arange(5.9)
f = np.arange(2, 7, dtype = float)
g = np.arange(2, 7, 2)
h = np.arange(2, 3, 0.2)
i = np.arange(10, 5, -1)

print(e, e.dtype)
print(f, f.dtype)
print(g, g.dtype)
print(h, h.dtype)
print(i, i.dtype)

[0. 1. 2. 3. 4. 5.] float64
[2. 3. 4. 5. 6.] float64
[2 4 6] int32
[2.  2.2 2.4 2.6 2.8] float64
[10  9  8  7  6] int32


### [예제3] reshape 메서드

In [8]:
# [1] 
# x의 개수와 reshape 개수가 반드시 같아야함!

x = np.arange(12)
r1 = np.reshape(x, (3,4))
r2 = x.reshape(3,4)
r3 = np.arange(12).reshape(4,3)

print(r1)
print(r2)
print(r3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# [2] 
# -1(음수) -> 해당 축은 item수 자동 계산

a = np.array([[1,2,3],[4,5,6]])
r3 = a.reshape(-1,3)        # 0축 item 수 자동계산
r4 = a.reshape(3, -3768743) # 1축 item 수 자동계산
r5 = a.reshape(-1)

print(r3, r3.shape)
print(r4, r4.shape)
print(r5, r5.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


### [예제4] ndarry 연산

In [10]:
# [1]
# element-wise : 배열간의 연산은 대응되는 item 간의 연산

a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
r1 = a1 + a2

prt(r1)

[ 6  8 10 12]



In [11]:
# [2
# Broadcasting : array끼리 계산시 shape이 다르면 맞춰주기
# item수가 1인 배열이 상대편 동일축 item 수 만큼 확장
# 우측 align, 확장된 축은 요소수 1로 생성

a1 = np.array([1,2,3,4])
a3 = np.arange(12).reshape(3,4)  # [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
r2 = a3 + 1   # [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
r3 = a3 + a1  # [[1,3,5,7],[5,7,9,11],[9,11,13,15]]

prt(a1, a3, r2, r3)

[1 2 3 4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]



In [12]:
# [3] 
# boolean array : 연산 결과가 bool인 경우 boolean array 생성

a3 = np.arange(12).reshape(3,4)  # [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
r4 = a3 > 2  # scalar 2를 (3,4) array로 broadcasting
             # 연산결과 bool이므로 "boolean array" 생성
prt(r4) 

[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]



In [13]:
# [4] 
# Upcasting : 다른 타입 간 연산 시 큰 타입으로 upcasting 되어 연산

a4 = np.array([1,2]) # type = int
a5 = np.array([1.0,2.0]) # type = float
r5 = a4 * a5 # 더 큰 타입인 float로 upcasting되어 연산

prt(a4, a5, r5)

[1 2]

[1. 2.]

[1. 4.]

